# NumPy
##### NumPy is a Python C extension library for array-oriented computing
    •Efficient
    •In-memory
    •Contiguous (or Strided)
    •Homogeneous (but types can be algebraic)
    
    NumPy is suited to many applications
    •Image processing
    •Signal processing
    •Linear algebra
    •A plethora of others

What is an array??
 - An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [ ]:
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 19 00:23:26 2019

@author: Sabie
"""
#Assigning Values
x=y=z=10
a,b,c=10,20,30
print(a,b,z)


#Keyword
#Identifiers
#Literals
#Operator


#Literals:
    #String Literals
        multiline='''Str1
        strr2,
        .....'''
    #Numeric:
    #    Int long float complex
    #Boolean:
    #Special - 
        None
#Operator:
        #Arithmatic Opr
        #Assignment Opr
            Var=10
            Var+=10
            Var*=10
        #Comparison Opr
        #Logical Opr
            a=10<10 and 2>-1
            a
        #Bitwise Opr
            7&5
            7|5
            4&5
            4|5
            ~7
            10>>2
            10<<2
        #Identiti Opr
            is
            is not
            Var is 200
            Var is not 200
        #Membership Opr
            in
            not in
            pets=['dog','cat','wolf']
            'lion' in pets
            'wolf' not in pets
            'me' in 'appointment'


# =============================================================================
# Datatype:
#     Immutable:
#         Strings:
            'hi' "Sabie" 
            '''kk
            kk
            kk'''
            str1='Hello World'
            print(str1[0:5])
            
            str1.find('or')#7
            
            str1.replace('or','OR')#'Hello WORld'
            
            str1.split(" ")#split functon
            str1.split('o')
            
            str1.count("o")#count 'o' in hello world
            str1.count('l')
            
            max(str1)#ASCI max value obtained
            min(str1)
            
#         Numbers:
            a=10.3
            int(a)
            complex(a) 
            type(a)
            type(str1)
            
#         Tuples:()
            my_tupple = ('a','b','c','d')
            my_tup=('e','f')
            #concatenation
            my_tupple+=my_tup
            my_tupple
            
            #repeatation
            my_tupple*2
            
            #indexing
            my_tupple[1]
            
            #slicing
            my_tupple[1:5]
#     Mutable:
#         Lists:[]
            myList=[]#empty list
            myList=['a',123,10.23,'John']
            list2=['Python',2]
            #concat
            myList+=list2
            print(myList)
            #repeatation
            myList*2
            #slicing
            myList[-2]
            #append
            myList.append("10")
            myList.append(list2)
            myList.append(10)
            #extend
            myList.extend(list2)
            myList.extend("10")
            myList.extend(10)#TypeError: 'int' object is not iterable
            #insert
            myList.insert(1,3000)
            myList.insert(3,list2)
            #remove  - by value
            myList.remove(3000)
            myList.remove('Python')#not in list
            myList[2].remove('Python')
            #pop - delete by index
            myList.pop(2)
            
            type(myList)
            
#         Dictionaries:{} Keys and values
            myDict={}#empty Dict
            myDict={1:[10,20,30],'fruits':["apple","banana","mango"],2:'Human'}
            #key can be integer or string
            #paring
            myDict=dict([(1,[10,20,30]),('fruits',["apple","banana","mango"]),(2,'Human')])
            #accesing dict by keys
            myDict[1]
            myDict['fruits']
            myDict[:]#no slicing
            myDict[1][1:]
            myDict['fruits'][-1]
            #length 
            len(myDict)#3 elements
            #keys
            myDict.keys()
            #Values
            myDict.values()
            #__contains__
            myDict.__contains__('fruits')
            #deleting all elements - Clear all
            myDict.clear()
            #deleting last keys
            myDict.popitem()
            #deleying by index
            myDict.pop(1)
            
            
#         Sets:{}
            
# =============================================================================

# =============================================================================
# Flow Control
# =============================================================================
if
for
while
break
continue
pass

# =============================================================================

# =============================================================================
# Functions
# Lambda
# =============================================================================

# =============================================================================
# File Handling:
# =============================================================================
# Open
f=open("C:/Users/acer/Desktop/Python Classnotes/Python Part 2/Topics.txt")
f.read
# Read
# Write/Create
# Delete
# 
# =============================================================================


# ============================================================================= 
# NUMPY
# =============================================================================
#Python List with some added features
import numpy as np

#1-D Array
a=np.array([1,2,3])#list
b=np.array((1,2,3))#tupple
print(a,b)
#now the tupple become list and it can be editable
b[1]=4
b#see

#2-D Array
a=np.array([[1,2,3],[4,5,6]])
a

#3-D array
a=np.array([[[1,2,3],[4,5,6]],[7,8,9]])
a
a=np.ndarray([2,2])

a[0]
a[0][1]

#numpy array initialisation
a=np.zeros((3,4))#np.zeros((row,column))
a
#ndarray
a=np.ndarray((3,5),dtype= int)#arg = shape
a

#a-range
a=np.arange(10,25,2)#np.arange([start,end(excluding),steps])
a

#linspace
a=np.linspace(5,6,10)#start,endpoint,no_of_interval_between_start_and _end
a

#fill with same valyes
a=np.full((3,4),6)#shape,value
a

#random 
a=np.random.random((3,4));a#ARG = SHAPE, 0-1

#0-1
np.random.rand(2)#1-D
np.random.rand(2,2)#2-D
np.random.rand(2,2,2)#3-D
np.random.rand(2,2,2,2)#4-D
#any random
np.random.randn(6)
np.random.randn(2,2)

np.random.random_integers(10,20,100)#100random int between 10and 20

a=np.random.randint(-10,10,100)#100random int between -10 and 10

np.random.random_sample(2)#2 random numbers

#shape function
a=np.array([[1,2,3],[4,5,6]])
a.shape#(2, 3)
#reshaping
a.shape=(3,2)
a.shape#(3, 2)
a#array([[1, 2],
  #     [3, 4],
   #    [5, 6]])
a.reshape((2,3))
#array([[1, 2, 3],
#       [4, 5, 6]])
a
#resizing same as reshape
a.resize((2,3))
a.shape[0]#row
a.shape[1]#column

a.size#6 no of items in a
a=np.arange(24)
a.size#24
a.shape(24,)
a.reshape(2,3,4)#3D,3rows,4columns; Not changes only shows
a.resize(6,2,2);a#3D,2Rows,2Col; changed the shape
a.shape
a.ndim#3D
a.dtype#int32
a=np.linspace(5,6,10)
a.dtype#float64

#NUMPY is used for number math and linear algebra; only int and float can be used
#Aggregate Function in numpy
a=np.array([10,20])
b=np.array([4,4])
a.sum()
np.sum(a)
np.sum((a,b))#38
np.subtract(a,b)#array([ 6, 16])
np.sum((a,b),axis=1)#array([30,  8]) - row wise
np.sum((a,b),axis=0)#array([14, 24]) - col wise
np.divide(a,b)#array([2.5, 5. ])
np.multiply(a,b)#array([40, 80])
np.exp(a)
np.exp2(a)
np.sqrt(a)
np.sin(a)
np.log(a)
np.lcm(10,20)
np.min(a)
np.min((a,b))
np.mean((a,b))#9.5
np.median((a,b))
np.corrcoef(a)
np.corrcoef((a,b))

#Equal comparison
np.equal(a,b)# array([False, False])
np.array_equal(a,b)#False

#Numpy BroadCasting
a=np.array([[1,3,5],[2,4,6]])
b=np.array([10,10,10])
np.sum((a,b))
#[[11, 13, 15],
 #[12, 14, 16]]
c=np.array([[10,10,10],[20,20,20]])
np.sum((a,c),axis=0)
np.sum((a,c),axis=1)

#indexing
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a[0]
a[1]
a[:]
a[1,1]#5
a[1][1]#5
a[-2][-2]#5
a[:,1:]#col2 onwards
a[2:,1]
a[:2,2:]

#array manipulation
b=np.array([[10,10,10],[20,20,20],[30,30,30]])
np.concatenate((a,b),axis=1)
#array([[ 1,  2,  3, 10, 10, 10],
 #      [ 4,  5,  6, 20, 20, 20],
  #     [ 7,  8,  9, 30, 30, 30]])
np.concatenate((a,b),axis=0)
#array([[ 1,  2,  3],
 #      [ 4,  5,  6],
  #     [ 7,  8,  9],
   #    [10, 10, 10],
    #   [20, 20, 20],
     #  [30, 30, 30]])
np.vstack((a,b))
np.hstack((a,b))
np.column_stack((a,b))


    #More convenient

# =============================================================================

# =============================================================================
# Pandas
# =============================================================================
    import pandas as pd
# Series
    a=[1,2,3]
    b=[[1,2,3],[5,6]]
    s=pd.Series(a)
    s=pd.Series(b)
  #indexing
      s=pd.Series(a,index=['a','b','c'])
      print(s)
      s[1:3]
      s['a':'c']
      s.a
    
# DataFrame
# =============================================================================




In [1]:
#Loading NumPy library
import numpy as np

## Python Lists vs. Numpy Arrays - What is the difference?
##### The answer is performance. 
Numpy data structures perform better in:

    Size - Numpy data structures take up less space
    Performance - they have a need for speed and are faster than lists
    Functionality - SciPy and NumPy have optimized functions such as linear algebra

Lets check it

In [3]:
#Advantages of Numpy:
#Consume less memory
import sys
#list
l=range(1000)
len(l)
print('List Size: ',sys.getsizeof(l)*len(l))#48000
#28 byte for one object, 14 for object, 2 for pointer
        
#numpy
a=np.arange(1000)
print('Numpy: ',a.size*a.itemsize)#4000
#4 byte pers item

List Size:  48000
Numpy:  4000


In [6]:
#Faster
import time
def usinglist(r=100000):
            t=time.time()
            x=range(r)
            y=range(r)
            z=[x[i]+y[i] for i in range(len(x))]
            return time.time()-t
        
def usingnumpy(r=100000):
            t=time.time()
            a=np.arange(r)
            b=np.arange(r)
            z=a+b#convinience
            return time.time()-t

In [10]:
print(usinglist())
print(usingnumpy())
usinglist()/usingnumpy()

0.08797693252563477
0.0


28.02954165671998

In [12]:
print(usinglist(100000000))
print(usingnumpy(100000000))
usinglist(10000000)/usingnumpy(10000000)

96.05659627914429
2.989419460296631


74.12546823622756

#### Numpy Array

In [13]:
#1-D Array
a=np.array([1,2,3])#list
b=np.array((1,2,3))#tupple
print(a,b)

[1 2 3] [1 2 3]


In [14]:
type(a)

numpy.ndarray

In [17]:
b[2]=5;b#tupple is now mutable

array([1, 2, 5])

In [27]:
#2-D Array
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
#3-D array
a=np.array([[[1,2,3],[4,5,6]],[7,8,9]])
a

array([list([[1, 2, 3], [4, 5, 6]]), list([7, 8, 9])], dtype=object)

In [21]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3]);arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

#### Check dimension of array

In [22]:
## check the shape of the array
arr.shape

(3, 5)

In [24]:
# Get Dimension
arr.ndim

2

In [30]:
a.ndim

1

In [32]:
# Get Type
arr.dtype

dtype('int32')

In [34]:
# Get Size
arr.itemsize

4

In [36]:
# Get total size
arr.nbytes

60

In [38]:
# Get number of elements
arr.size

15

#### Accessing/Changing specific elements, rows, columns, etc

In [43]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],
              [15,16,17,18,19,20,21]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


In [44]:
# Get a specific element [r, c]
a[1,5]

13

In [45]:
# Get a specific column
a[:,1]

array([ 2,  9, 16])

In [46]:
# Get a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [48]:
#Indexing first and last row
a[[0,-1],:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [15, 16, 17, 18, 19, 20, 21]])

In [51]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[1,0:-1:2]

array([ 8, 10, 12])

In [54]:
a[1,5] = 200
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12 200  14]
 [ 15  16  17  18  19  20  21]]


In [56]:
a[:,2] = [30,31,32]
print(a)

[[  1   2  30   4   5   6   7]
 [  8   9  31  11  12 200  14]
 [ 15  16  32  18  19  20  21]]


In [57]:
#3D 
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [58]:
# Get specific element (work outside in)
b[0,1,1]

4

In [61]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [63]:
# replace 
b[:,1,:] = [[9,9,],[8,8]];b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

#### Initializing Different Types of Arrays

In [64]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [66]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [67]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [71]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.39534509, 0.71457267],
       [0.30826282, 0.3546528 ],
       [0.4500771 , 0.94125002],
       [0.57281491, 0.44478529]])

In [69]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 5,  2,  5],
       [-3,  0,  6],
       [-2,  7,  1]])

In [72]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [76]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [80]:
#ndarray
a=np.ndarray((2,2,2),dtype= int)#arg = shape
a

array([[[1867404600,        512],
        [1915222968,        512]],

       [[ 247335406, 1365570291],
        [1974641136,        512]]])

In [81]:
#a-range
a=np.arange(10,25,2)#np.arange([start,end(excluding),steps])
a

array([10, 12, 14, 16, 18, 20, 22, 24])

In [82]:
#linspace
a=np.linspace(5,6,10)#start,endpoint,no_of_interval_between_start_and _end
a

array([5.        , 5.11111111, 5.22222222, 5.33333333, 5.44444444,
       5.55555556, 5.66666667, 5.77777778, 5.88888889, 6.        ])

In [84]:
np.random.rand(2)#1-D
np.random.rand(2,2)#2-D
np.random.rand(2,2,2)#3-D

array([[[0.92408289, 0.39450427],
        [0.3940618 , 0.88053982]],

       [[0.99101055, 0.84060865],
        [0.06266536, 0.41164558]]])

In [85]:
np.random.rand(2,2,2,2)#4-D

array([[[[0.55270905, 0.22488649],
         [0.27194231, 0.79903119]],

        [[0.10024478, 0.66861917],
         [0.8541947 , 0.98290494]]],


       [[[0.78744234, 0.09226231],
         [0.43996542, 0.97982472]],

        [[0.66935284, 0.14303832],
         [0.41824822, 0.76411355]]]])

In [86]:
np.random.random_sample(4)

array([0.55847971, 0.0836792 , 0.55462936, 0.96440928])

#### Math

In [87]:
#Numpy vs List
a = np.array([1,2,3,4])
l=[1,2,3,4]
print(a);print(l)

[1 2 3 4]
[1, 2, 3, 4]


In [88]:
print(a+2);print(l+2)

[3 4 5 6]


TypeError: can only concatenate list (not "int") to list

In [89]:
print(a*2);print(l*2)

[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]


In [90]:
print(a/2);print(l/2)

[0.5 1.  1.5 2. ]


TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [91]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [92]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [93]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [96]:
b=np.array([1.50,2.256,3.89,-6.12,-7.8])

Rounding

In [98]:
#Evenly round to the given number of decimals.
np.around(b,1)#

array([ 1.5,  2.3,  3.9, -6.1, -7.8])

In [99]:
np.round(b)

array([ 2.,  2.,  4., -6., -8.])

In [100]:
np.rint(b)#Round elements of the array to the nearest integer.

array([ 2.,  2.,  4., -6., -8.])

In [102]:
np.floor(b)

array([ 1.,  2.,  3., -7., -8.])

In [103]:
np.ceil(b)

array([ 2.,  3.,  4., -6., -7.])

In [104]:
np.trunc(b)#Return the truncated value of the input, element-wise.

array([ 1.,  2.,  3., -6., -7.])

In [105]:
np.fix(b)

array([ 1.,  2.,  3., -6., -7.])

Arithmetic operations

In [111]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,200,8000])
a+b

array([[  11,  202, 8003],
       [  14,  205, 8006]])

In [112]:
a.sum()

21

In [113]:
np.sum(b)

8210

In [114]:
np.sum((a,b))

array([[  11,  202, 8003],
       [  14,  205, 8006]])

In [122]:
b=np.random.randint(3,10,size=(2,3));b
np.sum((a,b),axis=1)

array([[ 5,  7,  9],
       [17, 12, 11]])

In [123]:
np.sum((a,b),axis=0)

array([[10, 10, 10],
       [12,  9, 10]])

In [124]:
b

array([[9, 8, 7],
       [8, 4, 4]])

In [125]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
np.prod((a,b),axis=1)

array([[ 4, 10, 18],
       [72, 32, 28]])

In [181]:
a=np.array([[1,2],[3,4]]); b=np.array([[-1,-3],[-10,-6]])
print(np.subtract(a,b))
print(np.divide(a,b))
print(np.multiply(a,b))

[[ 2  5]
 [13 10]]
[[-1.         -0.66666667]
 [-0.3        -0.66666667]]
[[ -1  -6]
 [-30 -24]]


In [131]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [134]:
np.cumsum((a,b),axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 10, 10],
        [12,  9, 10]]], dtype=int32)

In [138]:
np.diff((a))

array([[1, 1],
       [1, 1]])

In [139]:
np.exp(a)#Calculate the exponential of all elements in the input array.

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [142]:
np.expm1(a)#Calculate exp(x) - 1 for all elements in the array.

array([[  1.71828183,   6.3890561 ,  19.08553692],
       [ 53.59815003, 147.4131591 , 402.42879349]])

In [143]:
np.exp2(a)#Calculate 2**p for all p in the input array.

array([[ 2.,  4.,  8.],
       [16., 32., 64.]])

In [144]:
np.log(a)#Natural logarithm, element-wise.

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [145]:
np.log10(a)#Return the base 10 logarithm of the input array, element-wise.

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [146]:
np.log2(a)#Base-2 logarithm of x.

array([[0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 ]])

In [147]:
np.log1p(a)#Return the natural logarithm of one plus the input array, element-wise.

array([[0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015]])

In [155]:
np.lcm(12,18)

36

In [156]:
np.gcd(12,18)

6

In [157]:
np.min(a)

1

In [158]:
np.min((a,b))

1

In [159]:
np.min((a,b),axis=1)

array([[1, 2, 3],
       [8, 4, 4]])

In [163]:
np.mean((a,b))

5.083333333333333

In [164]:
np.mean((a,b),axis=1)

array([[2.5, 3.5, 4.5],
       [8.5, 6. , 5.5]])

In [166]:
np.median((a,b))

4.5

In [167]:
np.corrcoef(a,b)

array([[ 1.       ,  1.       , -1.       , -0.8660254],
       [ 1.       ,  1.       , -1.       , -0.8660254],
       [-1.       , -1.       ,  1.       ,  0.8660254],
       [-0.8660254, -0.8660254,  0.8660254,  1.       ]])

In [170]:
# Find the determinant
c=np.random.rand(3,3)
print(c)
np.linalg.det(c)

[[0.45503307 0.64228517 0.84340645]
 [0.93484338 0.89452113 0.67773348]
 [0.2309581  0.97492209 0.65510911]]


0.26761564998859505

#### Reorganizing Arrays

In [175]:
print(a)
a=a.reshape(1,6);a

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3, 4, 5, 6]])

In [176]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [177]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [187]:
np.column_stack((v1,v2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [179]:
# Horizontal  stack
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [182]:
a.resize(2,3)

In [183]:
a

array([[1, 2, 3],
       [4, 0, 0]])

In [184]:
a.resize(3,2);a

array([[1, 2],
       [3, 4],
       [0, 0]])

In [191]:
#Equal comparison
a=np.ones((2,2))
np.equal(a,b)

array([[False, False],
       [False, False]])

In [194]:
np.array_equal(a,b)

False

In [195]:
#Numpy BroadCasting
a=np.array([[1,3,5],[2,4,6]])
b=np.array([10,10,10])
np.sum((a,b))

array([[11, 13, 15],
       [12, 14, 16]])

In [197]:
#array manipulation
a=np.random.randint(1,10,size=(3,3))
b=np.array([[10,10,10],[20,20,20],[30,30,30]])
np.concatenate((a,b),axis=1)

array([[ 5,  5,  2, 10, 10, 10],
       [ 7,  1,  7, 20, 20, 20],
       [ 4,  7,  2, 30, 30, 30]])

In [198]:
np.concatenate((a,b),axis=0)

array([[ 5,  5,  2],
       [ 7,  1,  7],
       [ 4,  7,  2],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [200]:
np.unique(a)

array([1, 2, 4, 5, 7])

In [201]:
a.ravell()#To make nD array into 1 D)

array([5, 5, 2, 7, 1, 7, 4, 7, 2])