## NumPy Assignment

In [1]:
# 1. Create a 1-D array (Numbers_array) with the following values : [23, 56, 23, 34, 56, 76, 52, 51, 63, 82, 73]
import numpy as np
Numbers_array=np.array([23, 56, 23, 34, 56, 76, 52, 51, 63, 82, 73])

In [2]:
# a. Find the 4th element of Numbers_array.
Numbers_array[3]

34

In [3]:
# b. Find the 1st element of Numbers_array.
Numbers_array[0]

23

In [4]:
# c. Find first four elements of Numbers_array.
Numbers_array[:4]

array([23, 56, 23, 34])

In [7]:
# d. Create another array with the values [38, 99, 87, 67] and concatenate it with Numbers_array.
array2=np.array([38, 99, 87, 67])

In [9]:
np.append(Numbers_array,array2)

array([23, 56, 23, 34, 56, 76, 52, 51, 63, 82, 73, 38, 99, 87, 67])

In [10]:
# 2. Create a 2-D array (Numbers_array2) with the following values :
# [23, 56, 23, 34, 56, 76][52, 51, 63, 82, 73,58]
Numbers_array2=np.array([[23, 56, 23, 34, 56, 76],[52, 51, 63, 82, 73,58]])

In [11]:
# a. Find the length of Numbers_array2.
len(Numbers_array2)

2

In [12]:
# b. Find if 56 is present in Numbers_array2.
56 in Numbers_array2

True

In [13]:
# c. Find if 99 is present in Numbers_array2.
99 in Numbers_array2

False

In [14]:
# 3. Create two arrays with the following values :
# array1 = [23, 56, 23, 34, 56, 76, 52, 51, 63, 82, 73]
# array2 = [13, 46, 13, 36, 78, 61, 12, 70, 61, 13, 78]
array1 =np.array([23, 56, 23, 34, 56, 76, 52, 51, 63, 82, 73])
array2 =np.array([13, 46, 13, 36, 78, 61, 12, 70, 61, 13, 78])

In [17]:
# a. Add, Subtract, Multiply and Divide array1 and array2.
#sum
print('Sum: ',np.sum((array1,array2)))
print('ColSum: ',np.sum((array1,array2),axis=0))#colSum
print('RowSum: ',np.sum((array1,array2),axis=1))#rowSum
#subtract
print('Subtract: ',np.subtract(array1,array2))
#Multiply
print('Multiply: ',np.multiply(array1,array2))
#Division
print('Divide: ',np.divide(array1,array2))

Sum:  1070
ColSum:  [ 36 102  36  70 134 137  64 121 124  95 151]
RowSum:  [589 481]
Subtract:  [ 10  10  10  -2 -22  15  40 -19   2  69  -5]
Multiply:  [ 299 2576  299 1224 4368 4636  624 3570 3843 1066 5694]
Divide:  [1.76923077 1.2173913  1.76923077 0.94444444 0.71794872 1.24590164
 4.33333333 0.72857143 1.03278689 6.30769231 0.93589744]


In [18]:
array1+array2

array([ 36, 102,  36,  70, 134, 137,  64, 121, 124,  95, 151])

In [20]:
array1/array2

array([1.76923077, 1.2173913 , 1.76923077, 0.94444444, 0.71794872,
       1.24590164, 4.33333333, 0.72857143, 1.03278689, 6.30769231,
       0.93589744])

In [21]:
# b. Find sum and Product of array1.
#sum
np.sum(array1)

589

In [22]:
array1.sum()

589

In [23]:
#product
np.multiply(array1)

ValueError: invalid number of arguments

In [24]:
np.product(array1)

1828761600

In [25]:
# c. Find all the unique value of array2.
np.unique(array2)

array([12, 13, 36, 46, 61, 70, 78])

In [27]:
# d. Compare array1 & array2.
array1==array2

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [28]:
array1>array2

array([ True,  True,  True, False, False,  True,  True, False,  True,
        True, False])

In [29]:
array1<array2

array([False, False, False,  True,  True, False, False,  True, False,
       False,  True])

In [30]:
np.equal(array1,array2)

array([False, False, False, False, False, False, False, False, False,
       False, False])

### Duplicates 

In [32]:
#Find duplicates in array 2
def checkIfDuplicates(listOfElems):
    ''' Check if given list contains any duplicates '''
    if len(listOfElems) == len(set(listOfElems)):
        return False
    else:
        return True

checkIfDuplicates(array2)

True

In [41]:
def getDuplicatesWithCount(listOfElems):
    ''' Get frequency count of duplicate elements in the given list '''
    dictOfElems = dict()
    # Iterate over each element in list
    for elem in listOfElems:
    # If element exists in dict then increment its value else add it in dict
        if elem in dictOfElems:
            dictOfElems[elem] += 1
        else:
            dictOfElems[elem] = 1    
    # Filter key-value pairs in dictionary. Keep pairs whose value is greater than 1 i.e. only duplicate elements from list.
    dictOfElems = { key:value for key, value in dictOfElems.items() if value > 1}
        # Returns a dict of duplicate elements and thier frequency count
    return dictOfElems

In [42]:
# Get a dictionary containing duplicate elements in list and their frequency count
dictOfElems = getDuplicatesWithCount(array2)     
 
for key, value in dictOfElems.items():
    print(key , ' :: ', value)

13  ::  3
78  ::  2
61  ::  2
